# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: realityapi.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'realityapi.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10realityapi.proto\x12\nrealityapi\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"\x15\n\x05Hello\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x14\n\x04Text\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x7f\n\x06Packet\x12\"\n\x05hello\x18\x01 \x01(\x0b\x32\x11.realityapi.HelloH\x00\x12 \n\x04text\x18\x02 \x01(\x0b\x32\x10.realityapi.TextH\x00\x12\'\n\x08position\x18\x03 \x01(\x0b\x32\x13.realityapi.Vector3H\x00\x42\x06\n\x04\x62odyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'realityapi_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VECTOR3']._serialized_start=32
  _globals['_VECTOR3']._serialized_end=74
  _globals['_HELLO']._serialized_start=76
  _globals['_HELLO']._serialized_end=97
  _globals['_TEXT']._serialized_start=99
  _globals['_TEXT']._serialized_end=119
  _globals['_PACKET']._serialized_start=121
  _globals['_PACKET']._serialized_end=248
# @@protoc_insertion_point(module_scope)
