# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: realityapi.proto
# Protobuf Python Version: 7.36.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    0,
    '',
    'realityapi.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10realityapi.proto\x12\nrealityapi\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"\x15\n\x05Hello\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x14\n\x04Text\x12\x0c\n\x04text\x18\x01 \x01(\t\"!\n\tHeartbeat\x12\x14\n\x0c\x63urrent_time\x18\x01 \x01(\x01\"\x91\x01\n\x06Packet\x12%\n\x08position\x18\x03 \x01(\x0b\x32\x13.realityapi.Vector3\x12*\n\ndevicetype\x18\x04 \x01(\x0e\x32\x16.realityapi.DeviceType\x12\n\n\x02id\x18\x05 \x01(\t\x12(\n\theartbeat\x18\x06 \x01(\x0b\x32\x15.realityapi.Heartbeat*:\n\nDeviceType\x12\x06\n\x02VR\x10\x00\x12\x06\n\x02\x41R\x10\x01\x12\x07\n\x03\x44OG\x10\x02\x12\x07\n\x03\x41RM\x10\x03\x12\n\n\x06TURTLE\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'realityapi_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEVICETYPE']._serialized_start=304
  _globals['_DEVICETYPE']._serialized_end=362
  _globals['_VECTOR3']._serialized_start=32
  _globals['_VECTOR3']._serialized_end=74
  _globals['_HELLO']._serialized_start=76
  _globals['_HELLO']._serialized_end=97
  _globals['_TEXT']._serialized_start=99
  _globals['_TEXT']._serialized_end=119
  _globals['_HEARTBEAT']._serialized_start=121
  _globals['_HEARTBEAT']._serialized_end=154
  _globals['_PACKET']._serialized_start=157
  _globals['_PACKET']._serialized_end=302
# @@protoc_insertion_point(module_scope)
